/* 
 * Authorization API
 *
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.598
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Genesys.Authorization.Model
{
    /// <summary>
    /// ApiRequestDomainLookupOperation
    /// </summary>
    [DataContract]
    public partial class ApiRequestDomainLookupOperation :  IEquatable<ApiRequestDomainLookupOperation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiRequestDomainLookupOperation" /> class.
        /// </summary>
        /// <param name="Data">Data.</param>
        /// <param name="OperationId">Used for asynchronous operations to map request and response.</param>
        public ApiRequestDomainLookupOperation(DomainLookupOperation Data = default(DomainLookupOperation), string OperationId = default(string))
        {
            this.Data = Data;
            this.OperationId = OperationId;
        }
        
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public DomainLookupOperation Data { get; set; }
        /// <summary>
        /// Used for asynchronous operations to map request and response
        /// </summary>
        /// <value>Used for asynchronous operations to map request and response</value>
        [DataMember(Name="operationId", EmitDefaultValue=false)]
        public string OperationId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiRequestDomainLookupOperation {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  OperationId: ").Append(OperationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ApiRequestDomainLookupOperation);
        }

        /// <summary>
        /// Returns true if ApiRequestDomainLookupOperation instances are equal
        /// </summary>
        /// <param name="other">Instance of ApiRequestDomainLookupOperation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiRequestDomainLookupOperation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Data == other.Data ||
                    this.Data != null &&
                    this.Data.Equals(other.Data)
                ) && 
                (
                    this.OperationId == other.OperationId ||
                    this.OperationId != null &&
                    this.OperationId.Equals(other.OperationId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Data != null)
                    hash = hash * 59 + this.Data.GetHashCode();
                if (this.OperationId != null)
                    hash = hash * 59 + this.OperationId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
