/* 
 * Authorization API
 *
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.681
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Genesys.Authorization.Model
{
    /// <summary>
    /// AuthSchemeLookupOperation
    /// </summary>
    [DataContract]
    public partial class AuthSchemeLookupOperation :  IEquatable<AuthSchemeLookupOperation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthSchemeLookupOperation" /> class.
        /// </summary>
        /// <param name="UserName">UserName.</param>
        /// <param name="Tenant">Tenant.</param>
        public AuthSchemeLookupOperation(string UserName = default(string), string Tenant = default(string))
        {
            this.UserName = UserName;
            this.Tenant = Tenant;
        }
        
        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [DataMember(Name="userName", EmitDefaultValue=false)]
        public string UserName { get; set; }
        /// <summary>
        /// Gets or Sets Tenant
        /// </summary>
        [DataMember(Name="tenant", EmitDefaultValue=false)]
        public string Tenant { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuthSchemeLookupOperation {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Tenant: ").Append(Tenant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AuthSchemeLookupOperation);
        }

        /// <summary>
        /// Returns true if AuthSchemeLookupOperation instances are equal
        /// </summary>
        /// <param name="other">Instance of AuthSchemeLookupOperation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthSchemeLookupOperation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.UserName == other.UserName ||
                    this.UserName != null &&
                    this.UserName.Equals(other.UserName)
                ) && 
                (
                    this.Tenant == other.Tenant ||
                    this.Tenant != null &&
                    this.Tenant.Equals(other.Tenant)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.UserName != null)
                    hash = hash * 59 + this.UserName.GetHashCode();
                if (this.Tenant != null)
                    hash = hash * 59 + this.Tenant.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
