/* 
 * Authorization API
 *
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.687
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Genesys.Authorization.Client.SwaggerDateConverter;

namespace Genesys.Authorization.Model
{
    /// <summary>
    /// DefaultOAuth2AccessToken
    /// </summary>
    [DataContract]
    public partial class DefaultOAuth2AccessToken :  IEquatable<DefaultOAuth2AccessToken>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultOAuth2AccessToken" /> class.
        /// </summary>
        /// <param name="AccessToken">the access token.</param>
        /// <param name="ExpiresIn">timeout (in seconds) before token expiration.</param>
        /// <param name="IdToken">id_token, see JWT standard for more details.</param>
        /// <param name="TokenType">the type of access token, always &#39;bearer&#39;.</param>
        public DefaultOAuth2AccessToken(string AccessToken = default(string), int? ExpiresIn = default(int?), string IdToken = default(string), string TokenType = default(string))
        {
            this.AccessToken = AccessToken;
            this.ExpiresIn = ExpiresIn;
            this.IdToken = IdToken;
            this.TokenType = TokenType;
        }
        
        /// <summary>
        /// the access token
        /// </summary>
        /// <value>the access token</value>
        [DataMember(Name="access_token", EmitDefaultValue=false)]
        public string AccessToken { get; set; }

        /// <summary>
        /// timeout (in seconds) before token expiration
        /// </summary>
        /// <value>timeout (in seconds) before token expiration</value>
        [DataMember(Name="expires_in", EmitDefaultValue=false)]
        public int? ExpiresIn { get; set; }

        /// <summary>
        /// id_token, see JWT standard for more details
        /// </summary>
        /// <value>id_token, see JWT standard for more details</value>
        [DataMember(Name="id_token", EmitDefaultValue=false)]
        public string IdToken { get; set; }

        /// <summary>
        /// the type of access token, always &#39;bearer&#39;
        /// </summary>
        /// <value>the type of access token, always &#39;bearer&#39;</value>
        [DataMember(Name="token_type", EmitDefaultValue=false)]
        public string TokenType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DefaultOAuth2AccessToken {\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  IdToken: ").Append(IdToken).Append("\n");
            sb.Append("  TokenType: ").Append(TokenType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DefaultOAuth2AccessToken);
        }

        /// <summary>
        /// Returns true if DefaultOAuth2AccessToken instances are equal
        /// </summary>
        /// <param name="other">Instance of DefaultOAuth2AccessToken to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DefaultOAuth2AccessToken other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AccessToken == other.AccessToken ||
                    this.AccessToken != null &&
                    this.AccessToken.Equals(other.AccessToken)
                ) && 
                (
                    this.ExpiresIn == other.ExpiresIn ||
                    this.ExpiresIn != null &&
                    this.ExpiresIn.Equals(other.ExpiresIn)
                ) && 
                (
                    this.IdToken == other.IdToken ||
                    this.IdToken != null &&
                    this.IdToken.Equals(other.IdToken)
                ) && 
                (
                    this.TokenType == other.TokenType ||
                    this.TokenType != null &&
                    this.TokenType.Equals(other.TokenType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AccessToken != null)
                    hash = hash * 59 + this.AccessToken.GetHashCode();
                if (this.ExpiresIn != null)
                    hash = hash * 59 + this.ExpiresIn.GetHashCode();
                if (this.IdToken != null)
                    hash = hash * 59 + this.IdToken.GetHashCode();
                if (this.TokenType != null)
                    hash = hash * 59 + this.TokenType.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
